name := "vscode"
packages := "code"
base_images := "
ghcr.io/m2giles/m2os:aurora
ghcr.io/m2giles/m2os:aurora-nvidia
ghcr.io/m2giles/m2os:bazzite
ghcr.io/m2giles/m2os:bazzite-deck
ghcr.io/m2giles/m2os:bluefin
ghcr.io/m2giles/m2os:bluefin-nvidia
ghcr.io/m2giles/m2os:cosmic
ghcr.io/m2giles/m2os:cosmic-nvidia
ghcr.io/m2giles/m2os:aurora-beta
ghcr.io/m2giles/m2os:aurora-nvidia-beta
ghcr.io/m2giles/m2os:bazzite-beta
ghcr.io/m2giles/m2os:bazzite-deck-beta
ghcr.io/m2giles/m2os:bluefin-beta
ghcr.io/m2giles/m2os:bluefin-nvidia-beta
ghcr.io/m2giles/m2os:cosmic-beta
ghcr.io/m2giles/m2os:cosmic-nvidia-beta
"
pre_commands := "rpm --import https://packages.microsoft.com/keys/microsoft.asc; echo -e '[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | tee /etc/yum.repos.d/vscode.repo > /dev/null"

import '../sysext.just'

all: default
