name := "microsoft-edge"
packages := "microsoft-edge-stable"
base_images := "
ghcr.io/m2giles/m2os:aurora
ghcr.io/m2giles/m2os:aurora-nvidia
ghcr.io/m2giles/m2os:bazzite
ghcr.io/m2giles/m2os:bazzite-deck
ghcr.io/m2giles/m2os:bluefin
ghcr.io/m2giles/m2os:bluefin-nvidia
ghcr.io/m2giles/m2os:cosmic
ghcr.io/m2giles/m2os:cosmic-nvidia
ghcr.io/m2giles/m2os:aurora-beta
ghcr.io/m2giles/m2os:aurora-nvidia-beta
ghcr.io/m2giles/m2os:bazzite-beta
ghcr.io/m2giles/m2os:bazzite-deck-beta
ghcr.io/m2giles/m2os:bluefin-beta
ghcr.io/m2giles/m2os:bluefin-nvidia-beta
ghcr.io/m2giles/m2os:cosmic-beta
ghcr.io/m2giles/m2os:cosmic-nvidia-beta
"
pre_commands := "rm -rf /opt; mkdir /opt; rpm --import https://packages.microsoft.com/keys/microsoft.asc; echo -e '[edge-yum]\nname=edge-yum\nbaseurl=https://packages.microsoft.com/yumrepos/edge/\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | tee /etc/yum.repos.d/edge.repo > /dev/null"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    ${SUDO} mv opt/microsoft/msedge usr/lib/microsoft-edge
    ${SUDO} rmdir opt/{microsoft,}
    ${SUDO} ln -sf /usr/lib/microsoft-edge/microsoft-edge usr/bin/microsoft-edge-stable
    ${SUDO} mkdir -p usr/share/icons/hicolor/{16x16/apps,24x24/apps,32x32/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps}
    for i in "16" "24" "32" "48" "64" "128" "256"; do
        ${SUDO} ln -sf /usr/lib/microsoft-edge/product_logo_$i.png usr/share/icons/hicolor/${i}x${i}/apps/microsoft-edge.png
    done
    ${SUDO} rm -rf etc
