name := "emacs"
packages := "emacs libvterm"
dnf_weak_deps := "false"
enable_repos := "updates"
base_images := "
ghcr.io/m2giles/m2os:aurora
ghcr.io/m2giles/m2os:aurora-nvidia
ghcr.io/m2giles/m2os:bazzite
ghcr.io/m2giles/m2os:bazzite-deck
ghcr.io/m2giles/m2os:bluefin
ghcr.io/m2giles/m2os:bluefin-nvidia
ghcr.io/m2giles/m2os:cosmic
ghcr.io/m2giles/m2os:cosmic-nvidia
ghcr.io/m2giles/m2os:aurora-beta
ghcr.io/m2giles/m2os:aurora-nvidia-beta
ghcr.io/m2giles/m2os:bazzite-beta
ghcr.io/m2giles/m2os:bazzite-deck-beta
ghcr.io/m2giles/m2os:bluefin-beta
ghcr.io/m2giles/m2os:bluefin-nvidia-beta
ghcr.io/m2giles/m2os:cosmic-beta
ghcr.io/m2giles/m2os:cosmic-nvidia-beta
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    #set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs
    while [[ -z "${EMACS_LSP_BOOSTER:-}" || "${EMACS_LSP_BOOSTER:-}" == "null" ]]; do
        EMACS_LSP_BOOSTER="$(curl -L https://api.github.com/repos/blahgeek/emacs-lsp-booster/releases/latest | jq -r '.assets[] | select(.name| test(".*musl[.]zip$")).browser_download_url')" || (true && sleep 5)
    done
    curl --retry 3 -Lo /tmp/emacs-lsp-booster.zip "$EMACS_LSP_BOOSTER"
    ${SUDO} unzip -d usr/bin/ /tmp/emacs-lsp-booster.zip

    EMACS_PATH="/usr/bin/emacs-pgtk"
    ETAGS_PATH="/usr/bin/emacs.etags"
    ETAGS_MAN_PATH="/usr/share/man/man1/etags.emacs.1.gz"
    ${SUDO} ln -sf "$EMACS_PATH" "usr/bin/emacs"
    ${SUDO} ln -sf "$ETAGS_PATH" "usr/bin/etags"
