name := "emacs"
packages := "emacs"
dnf_weak_deps := "false"
enable_repos := "updates"
base_images := "
ghcr.io/m2giles/m2os:aurora
ghcr.io/m2giles/m2os:aurora-nvidia
ghcr.io/m2giles/m2os:bazzite
ghcr.io/m2giles/m2os:bazzite-deck
ghcr.io/m2giles/m2os:bluefin
ghcr.io/m2giles/m2os:bluefin-nvidia
ghcr.io/m2giles/m2os:cosmic
ghcr.io/m2giles/m2os:cosmic-nvidia
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    #set -x

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    EMACS_PATH="/usr/bin/emacs-pgtk"
    ETAGS_PATH="/usr/bin/emacs.etags"
    ETAGS_MAN_PATH="/usr/share/man/man1/etags.emacs.1.gz"
    ${SUDO} ln -sf "$EMACS_PATH" "usr/bin/emacs"
    ${SUDO} ln -sf "$ETAGS_PATH" "usr/bin/etags"
    ${SUDO} ln -sf "$ETAGS_MAN_PATH" "usr/share/man/man1/etags.1.gz"
