name := "keepassxc"
packages := "keepassxc"
base_images := "
ghcr.io/m2giles/m2os:aurora
ghcr.io/m2giles/m2os:aurora-nvidia
ghcr.io/m2giles/m2os:bazzite
ghcr.io/m2giles/m2os:bazzite-deck
ghcr.io/m2giles/m2os:bluefin
ghcr.io/m2giles/m2os:bluefin-nvidia
ghcr.io/m2giles/m2os:cosmic
ghcr.io/m2giles/m2os:cosmic-nvidia
"

import '../sysext.just'

all: default
